version: '3.9'

services:
  app: 
    build: .
    restart: always
    ports: 
      - 8080:8080
    environment:
      - PAGE_ACCESS_TOKEN=value
      - VERIFY_TOKEN=value
      - PORT=8080
    volumes:
      - .:/app